# Generated by Django 3.2.3 on 2021-10-24 17:24

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0004_auto_20211024_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='product_banner_blurb',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
