# Generated by Django 3.2.3 on 2021-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0007_auto_20211024_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbanner',
            old_name='card_button_text_color',
            new_name='product_card_button_text_color',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__left', 'Left'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
