# Generated by Django 3.2.3 on 2021-10-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0023_auto_20211024_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpagecustomisation',
            old_name='about_section_left_image',
            new_name='about_page_left_image',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__center', 'Center'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
