# Generated by Django 3.2.3 on 2021-10-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0027_auto_20211025_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecustomisation',
            name='facebook_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecustomisation',
            name='instagram_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecustomisation',
            name='linkedin_link',
            field=models.URLField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecustomisation',
            name='twitter_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__right', 'Right'), ('text-align__center', 'Center'), ('text-align__left', 'Left')], default='text-align__left'),
        ),
    ]
