# Generated by Django 3.2.3 on 2021-10-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0028_auto_20211025_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialspagecustomisation',
            old_name='view_testimonial_button_background_color',
            new_name='drop_to_form_background_color',
        ),
        migrations.RenameField(
            model_name='testimonialspagecustomisation',
            old_name='view_testimonial_button_label',
            new_name='drop_to_form_label',
        ),
        migrations.RenameField(
            model_name='testimonialspagecustomisation',
            old_name='view_testimonial_button_label_color',
            new_name='drop_to_form_label_color',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__left', 'Left'), ('text-align__right', 'Right'), ('text-align__center', 'Center')], default='text-align__left'),
        ),
    ]
