# Generated by Django 3.2.3 on 2021-12-27 14:33

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0037_auto_20211220_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecustomisation',
            name='left_banner_image',
            field=smartfields.fields.ImageField(default='', upload_to='home_page_images'),
        ),
    ]
