# Generated by Django 3.2.3 on 2021-12-27 14:50

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_customisations', '0040_auto_20211227_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage_Customisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_styling', models.CharField(default='', max_length=100)),
                ('left_banner_image', smartfields.fields.ImageField(default='', upload_to='home_page_images')),
            ],
            options={
                'verbose_name_plural': '     Home Page',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='homepagecustomisation',
            name='left_banner_image',
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_button_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
        migrations.AlterField(
            model_name='homepagecustomisation',
            name='main_page_text_alignment',
            field=models.TextField(choices=[('text-align__center', 'Center'), ('text-align__left', 'Left'), ('text-align__right', 'Right')], default='text-align__left'),
        ),
    ]
