# Generated by Django 3.2.3 on 2021-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('your_thoughts', models.TextField(max_length=1000)),
                ('rating', models.CharField(blank=True, max_length=1, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
