# Generated by Django 3.2.3 on 2021-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='push_to_testimonial_page',
            field=models.BooleanField(default=False),
        ),
    ]
