# Generated by Django 3.2.3 on 2021-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonial_push_to_testimonial_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='your_thoughts',
            field=models.TextField(max_length=350),
        ),
    ]
