# Generated by Django 3.2.3 on 2021-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', help_text='This will be the category image', upload_to='category_images'),
        ),
    ]
