# Generated by Django 3.2.3 on 2021-12-10 14:32

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
