# Generated by Django 3.2.3 on 2021-12-20 19:40

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='all_products_description',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_display_description',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
